name: CI/CD - Deploy bomoko-fund App to Vercel

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Node.js and Yarn
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'yarn'  # Use Yarn caching

      - name: Install Dependencies
        run: yarn install --frozen-lockfile  # Ensures a clean install

      - name: Build Project
        run: yarn build  # Replace with your build script if different

      - name: Deploy to Vercel (Production)
        if: github.event_name == 'push'
        run: npx vercel --prod --token ${{ secrets.VERCEL_TOKEN }}

      - name: Deploy to Vercel (Preview)
        if: github.event_name == 'pull_request'
        run: npx vercel --token ${{ secrets.VERCEL_TOKEN }}

